name: Sync to Private Repo

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config credential.helper store

    - name: Get current branch name
      id: get_branch
      run: echo ::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)

    - name: Pull from Personal Repo
      run: |
        git pull --no-edit https://github.com/mcvain/Pulse.git ${{ steps.get_branch.outputs.branch }}

    - name: Push to Private Repo
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git push https://github.com/LuResearchGroup/Pulse.git ${{ steps.get_branch.outputs.branch }}
